version: "3.7"

services:
  nginx:
    image: nginx
    deploy:
      labels:
        edu.wm.restartService.schedule: "*/2 * * * *"

  nginx2:
    image: nginx
    deploy:
      labels:
        edu.wm.restartService.schedule: "@every 1m"
